site: https://www1.nyc.gov/site/buildings/industry/energy-efficiency-incentives.page

program_type: Local Building Incentive

selectors:
  title: "h1, .page-title, .program-title"
  funding: ".incentive-amount, .rebate-amount, .funding"
  deadline: ".deadline, .application-deadline, .expires"
  eligibility: ".eligibility, .requirements, .who-qualifies"

deep_links:
  selector: "a[href*='/buildings/']"
  attribute: "href"

auto_pdf_detection: true
pdf_min_size: 10000
pdf_max_size: 10000000

headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

rate_limit: 2
timeout: 30