-- IncentEdge Database Schema
-- Migration: 019_puerto_rico_dc_programs
-- Description: Add Puerto Rico and District of Columbia incentive programs
-- Date: 2026-03-02
-- Author: CoCo (AI Execution Partner)
-- Target: Supabase PostgreSQL 15 (project pzmunszcxmmncppbufoj)

-- ============================================================================
-- PUERTO RICO INCENTIVE PROGRAMS
-- ============================================================================

-- PR-1: Act 60 Export Services Tax Credit
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_percentage,
    status,
    administrator,
    administering_agency,
    source_url,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-ACT60-EXPORT',
    'Act 60 Export Services Tax Credit',
    'Act 60 Export',
    'Individual and business tax benefits for export services established businesses and entrepreneurs relocating to Puerto Rico. Provides 4-37% individual and corporate tax reduction.',
    '4–37% tax reduction for export services and investments in PR',
    'tax_credit',
    'state',
    'PR Economic Incentive',
    'state',
    'PR',
    'tax_credit',
    'percentage',
    0.3700,
    'active',
    'Puerto Rico Department of Treasury',
    'Puerto Rico Department of Treasury',
    'https://www.act60.pr/',
    true,
    ARRAY['for-profit', 'individual', 'startup'],
    NOW(),
    'Act 60 PR Official',
    0.95
);

-- PR-2: IRA Investment Tax Credit (Enhanced for PR)
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    technology_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_percentage,
    direct_pay_eligible,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-IRA-ITC',
    'Investment Tax Credit (ITC) - Puerto Rico',
    'PR IRA ITC',
    'Federal IRA Investment Tax Credit for clean energy projects in Puerto Rico. Enhanced to 30-40% with potential energy community bonuses for disaster recovery zones.',
    '30–40% federal tax credit for clean energy in Puerto Rico with energy community bonuses',
    'tax_credit',
    'federal',
    'IRA Clean Energy',
    ARRAY['clean-energy'],
    ARRAY['solar', 'battery_storage', 'geothermal', 'wind', 'fuel_cells'],
    'state',
    'PR',
    'tax_credit',
    'percentage',
    0.3500,
    true,
    'active',
    'Internal Revenue Service',
    'IRS / PR Treasury',
    true,
    ARRAY['for-profit', 'nonprofit', 'municipal'],
    NOW(),
    'IRA PR Official',
    0.98
);

-- PR-3: Municipal Energy Efficiency Program
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    technology_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_fixed,
    amount_min,
    amount_max,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-MUN-ENERGY',
    'Municipal Energy Efficiency Program',
    'PR Mun Energy',
    'Grants for municipal and public facility energy efficiency upgrades and renewable energy installations in Puerto Rico.',
    'Grants up to $2M for municipal energy efficiency and renewable energy',
    'grant',
    'state',
    'PR Energy Efficiency',
    ARRAY['clean-energy', 'municipal'],
    ARRAY['solar', 'efficiency', 'hvac'],
    'state',
    'PR',
    'grant',
    'variable',
    NULL,
    250000,
    2000000,
    'active',
    'Puerto Rico Energy Bureau',
    'Puerto Rico Energy Bureau',
    true,
    ARRAY['municipal', 'nonprofit'],
    NOW(),
    'PR Energy Bureau',
    0.85
);

-- PR-4: Resilience Bond Fund
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_min,
    amount_max,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-RESILIENCE',
    'Resilience Bond Fund',
    'PR Resilience',
    'Financing for hurricane-resilient housing reconstruction and disaster mitigation in approved zones of Puerto Rico.',
    'Loans up to $5M for resilient housing reconstruction in disaster zones',
    'loan',
    'state',
    'PR Disaster Recovery',
    'state',
    'PR',
    'loan',
    'variable',
    500000,
    5000000,
    'active',
    'Puerto Rico Department of Housing',
    'Puerto Rico Department of Housing',
    false,
    ARRAY['for-profit', 'nonprofit', 'municipal'],
    NOW(),
    'PR Housing Dept',
    0.80
);

-- PR-5: Solar Incentive & Net Metering
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    technology_types,
    jurisdiction_level,
    state,
    incentive_type,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-SOLAR-NET-METER',
    'Net Metering & Solar Incentive Program',
    'PR Solar',
    'Net metering credits and rebates for residential and commercial distributed solar installations in Puerto Rico. Variable by utility.',
    'Net metering credits and solar rebates for distributed generation',
    'rebate',
    'utility',
    'PR Solar',
    ARRAY['clean-energy', 'residential', 'commercial'],
    ARRAY['solar'],
    'utility',
    'PR',
    'rebate',
    'active',
    'Puerto Rico Energy Commission',
    'Puerto Rico Energy Commission',
    true,
    ARRAY['for-profit', 'nonprofit', 'residential'],
    NOW(),
    'PR Energy Commission',
    0.90
);

-- PR-6: Act 60 Startup Investor Credit
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_percentage,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'PR-ACT60-STARTUP',
    'Act 60 Startup Investor Tax Credit',
    'Act 60 Startup',
    'Tax credit for investors in Puerto Rico-based startups focused on innovation and tech sectors. 37% credit on investment.',
    '37% tax credit for startup investments in Puerto Rico tech companies',
    'tax_credit',
    'state',
    'PR Economic Incentive',
    'state',
    'PR',
    'tax_credit',
    'percentage',
    0.3700,
    'active',
    'Puerto Rico Department of Treasury',
    'Puerto Rico Department of Treasury',
    'https://www.act60.pr/',
    true,
    ARRAY['for-profit', 'individual', 'investor'],
    NOW(),
    'Act 60 PR Official',
    0.92
);

-- ============================================================================
-- DISTRICT OF COLUMBIA INCENTIVE PROGRAMS
-- ============================================================================

-- DC-1: DC LIHTC Program
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    building_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    status,
    administrator,
    administering_agency,
    source_url,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'DC-LIHTC',
    'DC Low-Income Housing Tax Credit (LIHTC)',
    'DC LIHTC',
    'Competitive 9% and 4% LIHTC allocation for affordable rental housing development throughout Washington DC under the annual QAP.',
    'Competitive 9% and 4% LIHTC for affordable rental housing in DC',
    'tax_credit',
    'federal',
    'Federal Housing',
    ARRAY['real-estate'],
    ARRAY['multifamily', 'mixed_use'],
    'state',
    'DC',
    'tax_credit',
    'percentage',
    'active',
    'DC Department of Housing and Community Development',
    'DHCD',
    'https://dhcd.dc.gov/',
    true,
    ARRAY['for-profit', 'nonprofit'],
    NOW(),
    'DC DHCD',
    0.96
);

-- DC-2: DC First Mortgage Loan Program
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    building_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_min,
    amount_max,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'DC-FIRST-MORTGAGE',
    'DC First Mortgage Loan Program',
    'DC First Mortgage',
    'Low-interest permanent financing for affordable rental housing development and preservation in Washington DC.',
    'First mortgage loans $1M–$15M for affordable housing at below-market rates',
    'loan',
    'state',
    'DC Housing Finance',
    ARRAY['real-estate'],
    ARRAY['multifamily', 'mixed_use'],
    'state',
    'DC',
    'loan',
    'variable',
    1000000,
    15000000,
    'active',
    'DC Department of Housing and Community Development',
    'DHCD',
    true,
    ARRAY['for-profit', 'nonprofit'],
    NOW(),
    'DC DHCD',
    0.94
);

-- DC-3: HOC Production (Housing Opportunities Commission)
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    building_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_min,
    amount_max,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'DC-HOC',
    'HOC Production - Housing Opportunities Commission',
    'DC HOC',
    'Direct production of affordable housing by the District agency serving very low-income residents. HOC develops, finances, and operates affordable housing.',
    'Direct affordable housing development by DC Housing Opportunities Commission',
    'grant',
    'state',
    'DC Housing Production',
    ARRAY['real-estate'],
    ARRAY['multifamily', 'mixed_use'],
    'state',
    'DC',
    'grant',
    'variable',
    2000000,
    25000000,
    'active',
    'DC Housing Opportunities Commission',
    'HOC',
    false,
    ARRAY['nonprofit', 'municipal'],
    NOW(),
    'DC HOC',
    0.92
);

-- DC-4: DC Property Tax Exemption for Affordable Housing
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    building_types,
    jurisdiction_level,
    state,
    incentive_type,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'DC-TAX-EXEMPT',
    'DC Property Tax Exemption for Affordable Housing',
    'DC Tax Exempt',
    'Property tax exemption for affordable housing developments meeting affordability and community service requirements in DC.',
    'Property tax exemption for qualified affordable housing projects',
    'tax_credit',
    'state',
    'DC Tax Exemption',
    ARRAY['real-estate'],
    ARRAY['multifamily', 'mixed_use'],
    'state',
    'DC',
    'tax_credit',
    'active',
    'DC Department of Housing and Community Development',
    'DHCD / Office of Tax and Revenue',
    true,
    ARRAY['nonprofit'],
    NOW(),
    'DC DHCD',
    0.88
);

-- DC-5: Office of Planning & Finance Initiatives (OPFI) Grants
INSERT INTO incentive_programs (
    external_id,
    name,
    short_name,
    description,
    summary,
    program_type,
    category,
    subcategory,
    sector_types,
    building_types,
    jurisdiction_level,
    state,
    incentive_type,
    amount_type,
    amount_min,
    amount_max,
    status,
    administrator,
    administering_agency,
    stackable,
    entity_types,
    last_verified_at,
    data_source,
    confidence_score
) VALUES (
    'DC-OPFI',
    'Office of Planning & Finance Initiatives Grants',
    'DC OPFI',
    'Development grants for mixed-income and workforce housing supporting DC economic development and revitalization.',
    'Grants up to $3M for mixed-income and workforce housing development',
    'grant',
    'state',
    'DC Economic Development',
    ARRAY['real-estate'],
    ARRAY['multifamily', 'mixed_use'],
    'state',
    'DC',
    'grant',
    'variable',
    250000,
    3000000,
    'active',
    'DC Office of Planning & Finance Initiatives',
    'OPFI',
    true,
    ARRAY['for-profit', 'nonprofit'],
    NOW(),
    'DC OPFI',
    0.85
);

-- ============================================================================
-- LOG SYNC EVENT
-- ============================================================================
INSERT INTO program_sync_log (
    sync_type,
    source,
    status,
    programs_added,
    programs_updated,
    triggered_by,
    metadata
) VALUES (
    'manual',
    'claude-code',
    'completed',
    11,
    0,
    NULL,
    jsonb_build_object(
        'migration', '019_puerto_rico_dc_programs',
        'reason', 'Add Puerto Rico and District of Columbia to incentive map',
        'territories_added', ARRAY['PR', 'DC']
    )
);
