-- Lead Capture Table for IncentEdge Pricing & Signup Flow
-- Captures user information when users download sample results
-- Supports rate limiting (max 1 report per month per email)

CREATE TABLE IF NOT EXISTS public.lead_captures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL,
  company_size VARCHAR(50), -- "1-10", "11-50", "50-200", "200+"
  industry VARCHAR(100), -- "Real Estate", "Clean Energy", "Utilities", etc
  project_address TEXT,
  project_type VARCHAR(100), -- "Commercial", "Residential", "Mixed-Use", "Solar", etc
  project_estimated_value DECIMAL(15,2),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  last_report_generated_at TIMESTAMP,
  report_count INTEGER DEFAULT 0,
  ip_address INET,
  user_agent TEXT,
  utm_source VARCHAR(100),
  utm_campaign VARCHAR(100),

  -- Indexing for performance
  CONSTRAINT email_not_empty CHECK (email != ''),
  CONSTRAINT valid_company_size CHECK (company_size IS NULL OR company_size IN ('1-10', '11-50', '50-200', '200+')),
  CONSTRAINT valid_report_count CHECK (report_count >= 0)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_lead_captures_email ON public.lead_captures(email);
CREATE INDEX IF NOT EXISTS idx_lead_captures_created_at ON public.lead_captures(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_captures_ip_address ON public.lead_captures(ip_address);
CREATE INDEX IF NOT EXISTS idx_lead_captures_utm ON public.lead_captures(utm_source, utm_campaign);
CREATE INDEX IF NOT EXISTS idx_lead_captures_last_report ON public.lead_captures(last_report_generated_at);

-- Enable RLS
ALTER TABLE public.lead_captures ENABLE ROW LEVEL SECURITY;

-- RLS: Allow anyone to insert new leads
CREATE POLICY "public_can_insert_leads" ON public.lead_captures
  FOR INSERT
  WITH CHECK (true);

-- RLS: Allow users to view leads by their email
CREATE POLICY "users_can_view_own_leads" ON public.lead_captures
  FOR SELECT
  USING (email = current_user_email() OR current_user_id() = auth.uid());

-- Helper function to check if user has already generated a report this month
CREATE OR REPLACE FUNCTION can_generate_report(user_email VARCHAR)
RETURNS TABLE (allowed BOOLEAN, last_report_date TIMESTAMP, days_until_next BIGINT) AS $$
BEGIN
  RETURN QUERY
  SELECT
    (last_report_generated_at IS NULL OR last_report_generated_at < NOW() - INTERVAL '30 days')::BOOLEAN AS allowed,
    last_report_generated_at,
    EXTRACT(EPOCH FROM (last_report_generated_at + INTERVAL '30 days' - NOW()))::BIGINT / 86400 AS days_until_next
  FROM public.lead_captures
  WHERE email = user_email
  ORDER BY last_report_generated_at DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Helper function to update report generation timestamp
CREATE OR REPLACE FUNCTION record_report_generation(user_email VARCHAR)
RETURNS void AS $$
BEGIN
  UPDATE public.lead_captures
  SET
    last_report_generated_at = NOW(),
    report_count = report_count + 1,
    updated_at = NOW()
  WHERE email = user_email
  ORDER BY created_at DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Add comment explaining the table
COMMENT ON TABLE public.lead_captures IS
'Stores lead information captured during free sample result downloads. Used for email nurture, conversion tracking, and product analytics.';

COMMENT ON COLUMN public.lead_captures.report_count IS
'Total number of reports generated by this lead. Max 1 per 30 days.';

COMMENT ON COLUMN public.lead_captures.last_report_generated_at IS
'Timestamp of most recent report download. Used to enforce monthly rate limit.';

COMMENT ON COLUMN public.lead_captures.utm_source IS
'Campaign source (e.g., "homepage", "ppc", "organic"). For attribution.';

COMMENT ON COLUMN public.lead_captures.utm_campaign IS
'Campaign name (e.g., "launch", "partner_promo"). For analytics.';
